import { Sidebar } from "@/components/dashboard/sidebar";
import MobileNavigator from "@/components/navbar/mobile-navigator";
import MobileViewNavbar from "@/components/navbar/mobile-view";
import Navbar from "@/components/navbar/navigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
        <Navbar />
        <MobileViewNavbar />

        <div className="app">
          <div className="flex">
            <div className="md:w-[5%] md:block hidden">
              <Sidebar />
            </div>
            <div className="w-[1%] md:block hidden"></div>
            <div className="bg-gray-100 md:rounded-l-xl rounded-none py-3 px-3  md:w-[94%] overflow-clip">
              {children}
            </div>
          </div>
        </div>
        {/* </ThemeProvider> */}

        <MobileNavigator />
      </body>
    </html>
  );
}
