import { Sidebar } from "@/components/dashboard/sidebar";
import Navbar from "@/components/navbar/navigation";
import { ThemeProvider } from "@/shadcn/ui/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className="app">
            <div className="flex">
              <div className="w-[5%]">
                <Sidebar />
              </div>
              <div className="w-[1%]"></div>
              <div className="bg-gray-100 rounded-l-xl p-2 w-[94%]">
                {children}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
